// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from "storyblok";
export interface RichtextStoryblok {
  type: string;
  content?: RichtextStoryblok[];
  marks?: RichtextStoryblok[];
  attrs?: unknown;
  text?: string;
}

export interface FaqStoryblok {
  question: string;
  answer: RichtextStoryblok;
  component: "faq";
  _uid: string;
}

export interface FaqListStoryblok {
  title: string;
  questions: (ISbStoryData<FaqStoryblok> | string)[];
  component: "faq_list";
  _uid: string;
}

export interface AssetStoryblok {
  alt?: string;
  copyright?: string;
  id: number;
  filename: string;
  name: string;
  title?: string;
  focus?: string;
}

export interface FooterStoryblok {
  logo: AssetStoryblok;
  content?: RichtextStoryblok;
  link_lists?: FooterLinkListStoryblok[];
  copyright: string;
  component: "footer";
  _uid: string;
}

export type MultilinkStoryblok =
  | {
      id?: string;
      cached_url?: string;
      anchor?: string;
      linktype?: "story";
      target?: "_self" | "_blank";
      story?: {
        name: string;
        created_at?: string;
        published_at?: string;
        id: number;
        uuid: string;
        content?: {};
        slug: string;
        full_slug: string;
        sort_by_date?: null | string;
        position?: number;
        tag_list?: string[];
        is_startpage?: boolean;
        parent_id?: null | number;
        meta_data?: null | {};
        group_id?: string;
        first_published_at?: string;
        release_id?: null | number;
        lang?: string;
        path?: null | string;
        alternates?: unknown[];
        default_full_slug?: null | string;
        translated_slugs?: null | unknown[];
      };
    }
  | {
      url?: string;
      cached_url?: string;
      anchor?: string;
      linktype?: "asset" | "url";
      target?: "_self" | "_blank";
    }
  | {
      email?: string;
      linktype?: "email";
      target?: "_self" | "_blank";
    };

export interface FooterLinkStoryblok {
  title: string;
  link: Exclude<MultilinkStoryblok, {linktype?: "asset"}>;
  component: "footer_link";
  _uid: string;
}

export interface FooterLinkListStoryblok {
  title?: string;
  links: FooterLinkStoryblok[];
  component: "footer_link_list";
  _uid: string;
}

export type MultiassetStoryblok = {
  alt?: string;
  copyright?: string;
  id: number;
  filename: string;
  name: string;
  title?: string;
}[];

export interface MealStoryblok {
  title?: string;
  body?: RichtextStoryblok;
  images: MultiassetStoryblok;
  tags?: (ISbStoryData<MealTagStoryblok> | string)[];
  component: "meal";
  _uid: string;
}

export interface MealTagStoryblok {
  title?: string;
  color: "" | "green" | "red" | "gold";
  component: "meal_tag";
  _uid: string;
}

export interface NavStoryblok {
  logo: AssetStoryblok;
  nav_items: NavItemStoryblok[];
  component: "nav";
  _uid: string;
}

export interface NavItemStoryblok {
  title?: string;
  icon?: AssetStoryblok;
  link: Exclude<MultilinkStoryblok, {linktype?: "asset"}>;
  component: "nav_item";
  _uid: string;
}

export interface PageStoryblok {
  nav: (ISbStoryData<NavStoryblok> | string)[];
  meta_title?: string;
  meta_description?: string;
  body?: (
    | FaqStoryblok
    | FaqListStoryblok
    | FooterStoryblok
    | FooterLinkStoryblok
    | FooterLinkListStoryblok
    | MealStoryblok
    | MealTagStoryblok
    | NavStoryblok
    | NavItemStoryblok
    | PageStoryblok
    | ProductStoryblok
    | ProductTagStoryblok
    | TestimonialStoryblok
    | TestimonialListStoryblok
    | TestimonialSourceStoryblok
  )[];
  footer: (ISbStoryData<FooterStoryblok> | string)[];
  component: "page";
  _uid: string;
}

export interface ProductStoryblok {
  title: string;
  body: RichtextStoryblok;
  images: MultiassetStoryblok;
  tags?: (ISbStoryData<ProductTagStoryblok> | string)[];
  component: "product";
  _uid: string;
}

export interface ProductTagStoryblok {
  title: string;
  color: "" | "green" | "red" | "gold";
  component: "product_tag";
  _uid: string;
}

export interface TestimonialStoryblok {
  author_name: string;
  rating: "" | "1" | "2" | "3" | "4" | "5";
  content: string;
  source: string;
  component: "testimonial";
  _uid: string;
}

export interface TestimonialListStoryblok {
  title: string;
  sources: TestimonialSourceStoryblok[];
  testimonials: (ISbStoryData<TestimonialStoryblok> | string)[];
  component: "testimonial_list";
  _uid: string;
}

export interface TestimonialSourceStoryblok {
  title: string;
  logo: AssetStoryblok;
  average_rating: string;
  component: "testimonial_source";
  _uid: string;
}
